<Card :valkyrie="valkyrie" :signets="signets" />
</template>

<script setup>
    import Card from '../../components/Card.vue';

    const valkyrie = {
        id: 5,
        name: 'Herrscher of Flamescion',
        imageSrc: '/images/herrscher-of-flamescion.jpg',
        imageAlt: 'Herrscher of Flamescion',
        position: 'object-[-4rem]',
    };

    const signets = {
        builds: [
            {
                id: 1,
                name: 'Recommendation',
                signets: [
                    {
                        id: 1,
                        name: 'Elysia',
                        lists: [
                            {
                                id: 1,
                                name: 'Blessing of Heatflow',
                                desc: 'Black holes generated by the Herrscher of Flamescion deal 75% bonus Fire DMG. Triggering Ultimate Evasion Skill creates an additional black hole',
                                priority: 'Start',
                            },
                            {
                                id: 2,
                                name: 'Blessing of Starfire',
                                desc: 'When a black hole created by the Herrscher of Flamescion ends, a smaller black hole lasting 5s is generated to deal 300% ATK of Fire DMG per second. CD: 3s',
                                priority: 'Filler (1st if low gear level)',
                            },
                            {
                                id: 3,
                                name: 'Blessing of Reburn',
                                desc: 'Triggering Ultimate Evasion Skill removes Overheat and clears Heat',
                                priority: '1st',
                            },
                            {
                                id: 4,
                                name: 'Blessing of Tempered Warrior',
                                desc: 'Aerial Combo ATKs reduce Ultimate Evasion Skill CD by 9s',
                                priority: '2nd',
                            },
                            {
                                id: 5,
                                name: 'Blessing of Flamescion',
                                desc: 'For every black hole created by the Herrscher of Flamescion, Valkyrie restores 25 HP per second and deals 30% bonus Total DMG',
                                priority: 'Filler',
                            }
                        ],
                    },
                    {
                        id: 2,
                        name: 'Sakura 1',
                        lists: [
                            {
                                id: 1,
                                name: 'Bountiful Blossom: Koyo',
                                desc: 'Triggering Ultimate Evasion Skill boosts Total DMG taken by all enemies by 30% for 8s',
                                priority: '1st',
                            },
                            {
                                id: 2,
                                name: 'Bountiful Blossom: Fuji',
                                desc: 'Ultimate Evasion Skill has 1 more charge and 10% reduced CD',
                                priority: '2nd'
                            },
                            {
                                id: 3,
                                name: 'Bountiful Blossom: Ayame',
                                desc: 'Triggering Ultimate Evasion Skill restores 12.0 bonus SP',
                                priority: '3rd',
                            },
                            {
                                id: 4,
                                name: 'Nexus Signet: Setsuna Blade: Sakura-ni-Maku',
                                desc: 'Core',
                                priority: '',
                            },
                            {
                                id: 5,
                                name: 'Setsuna Blade: Ame-Shiko',
                                desc: 'Triggering Sakura Screen resets Weapon skill and Ultimate CD',
                                priority: 'YES',
                            }
                        ],
                    },
                    {
                        id: 3,
                        name: 'Kalpas 2',
                        lists: [
                            {
                                id: 1,
                                name: 'Desireless, Mindless, and Homeless',
                                desc: 'Losing HP boosts Total DMG taken by all enemies by 25% for 8s',
                                priority: '1st',
                            },
                            {
                                id: 2,
                                name: 'Path, Misfortune, and Written Fate',
                                desc: 'Max HP increases by 25%',
                                priority: '2nd',
                            },
                            {
                                id: 3,
                                name: 'Bone, Blood, and Ribbon',
                                desc: 'Every 100 HP loss boosts Physical & Elemental DMG by 0.8%',
                                priority: '3rd'
                            },
                            {
                                id: 4,
                                name: 'Blade, Grave, and Scar',
                                desc: 'Every 100 HP loss boosts Total DMG by 1%',
                                priority: '4th',
                            },
                            {
                                id: 5,
                                name: 'Nexus Signet: Soldiers, Scissors, Spoils, and Slaughter',
                                desc: 'Core',
                                priority: '',
                            },
                            {
                                id: 6,
                                name: 'Hometown, Homeland, Friends, and Acquaintances',
                                desc: 'If [Bloodboil Garment] exceeds 1500, gain 25% physical and elemental breach',
                                priority: 'YES',
                            },
                            {
                                id: 7,
                                name: 'Death, Life, Oblivion, and Existence',
                                desc: 'If [Bloodboil Garment] exceeds 1500, when taking damage, reduces damage taken by 1% of [Bloodboil Garment]',
                                priority: 'Filler'
                            }
                        ],
                    },
                    {
                        id: 4,
                        name: 'Su 2',
                        lists: [
                            {
                                id: 1,
                                name: 'Motto of Dibba-Cakkhu',
                                desc: 'Combo hits are reset at to boost Total DMG taken by all enemies by 35% for 10s',
                                priority: '1st'
                            },
                            {
                                id: 2,
                                name: 'Motto of Asavakkhaya',
                                desc: 'Attacks grant 25 bonus combo hits on hit. CD: 5s',
                                priority: '2nd',
                            },
                            {
                                id: 3,
                                name: 'Motto of Iddhi-Vidha',
                                desc: 'Combo hits are increased to 60 when below 60. CD: 10s',
                                priority: '3rd',
                            },
                            {
                                id: 4,
                                name: 'Nexus Signet: Dictum of Bodhi',
                                desc: 'Core',
                                priority: '',
                            },
                            {
                                id: 5,
                                name: 'Dictum of Anatman',
                                desc: 'The Bodhi: Eyes Open lasts for 3s longer. For every debuff on the target enemy, it takes 5% bonus Total DMG',
                                priority: 'Filler',
                            }
                        ],
                    },
                    {
                        id: 5,
                        name: 'Hua 2 (optional core; choose one or none)',
                        lists: [
                            {
                                id: 1,
                                name: 'Old Dreams Again',
                                desc: 'Elemental Breach increases by 0.6% per second',
                                priority: '1st'
                            },
                            {
                                id: 2,
                                name: 'Dark Garb No More',
                                desc: 'Elemental DMG increases by 0.8% per second',
                                priority: '2nd',
                            },
                            {
                                id: 3,
                                name: 'Long Trip',
                                desc: 'Total DMG increases by 1.0% per second. 40 stacks max. Taking DMG reduces 10 stacks',
                                priority: '3rd',
                            },
                            {
                                id: 4,
                                name: 'Nexus Signet: Suffering Mass',
                                desc: 'Core',
                                priority: '',
                            },
                            {
                                id: 5,
                                name: 'Worldly Troubles',
                                desc: "With Soldier's Remembrance, gain TDM equal to 50% of total damage reduction from signets",
                                priority: '1st',
                            },
                            {
                                id: 6,
                                name: 'Broken Dream',
                                desc: "When possessing Soldier's Remembrance, increase the maximum stack of normal Vicissitude signets by 20",
                                priority: 'YES'
                            }
                        ],
                    },
                    {
                        id: 6,
                        name: 'Eden 1 (optional core; choose one or none)',
                        lists: [
                            {
                                id: 1,
                                name: 'Recitatif of Creeks',
                                desc: 'Every 10 SP left boosts Physical & Elemental DMG by 2.5%',
                                priority: '1st',
                            },
                            {
                                id: 2,
                                name: 'Recitatif of Eden',
                                desc: 'Every 10 SP left boosts Total DMG by 3.0%',
                                priority: '2nd',
                            },
                            {
                                id: 3,
                                name: 'Recitatif of Good Wine',
                                desc: 'Restore 1.5 SP per second',
                                priority: '3rd',
                            },
                            {
                                id: 4,
                                name: 'Nexus Signet 1: Aria of Gold',
                                desc: 'Core',
                                priority: '',
                            },
                            {
                                id: 5,
                                name: 'Aria of Soil',
                                desc: 'Intoxicated enemies take only 10% bonus Total DMG but it can stack up to 3 times',
                                priority: '1st',
                            }
                        ],
                    },
                    {
                        id: 7,
                        name: 'Eden 2 (optional core; choose one or none)',
                        lists: [
                            {
                                id: 1,
                                name: 'Recitatif of Creeks',
                                desc: 'Every 10 SP left boosts Physical & Elemental DMG by 2.5%',
                                priority: '1st',
                            },
                            {
                                id: 2,
                                name: 'Recitatif of Eden',
                                desc: 'Every 10 SP left boosts Total DMG by 3.0%',
                                priority: '2nd',
                            },
                            {
                                id: 3,
                                name: 'Recitatif of Good Wine',
                                desc: 'Restore 1.5 SP per second',
                                priority: '3rd',
                            },
                            {
                                id: 4,
                                name: 'Nexus Signet: Echo of Gold',
                                desc: 'Core',
                                priority: '',
                            },
                            {
                                id: 5,
                                name: 'Echo of Silent Night',
                                desc: 'After lasting over 7s, reduce ATK, DEF, ele resists of enemies nearby',
                                priority: '1st',
                            },
                            {
                                id: 6,
                                name: 'Echo of Withered Soil',
                                desc: 'After lasting over 7s, boost SP cap and restore SP/s till it ends',
                                priority: 'Filler',
                            }
                        ],
                    },
                    {
                        id: 7,
                        name: 'Griseo 1 (optional core; choose one or none)',
                        lists: [
                            {
                                id: 1,
                                name: 'Red & Hot',
                                desc: 'Using a weapon active taints enemies nearby with red paint for 8s and makes them take 25% bonus Physical and Elemental MG (cannot stack). Triggering it again resets the duration',
                                priority: '1st',
                            },
                            {
                                id: 2,
                                name: 'Yellow & Warm',
                                desc: 'Using an Ultimate taints enemies nearby with yellow paint for 8s and makes them take 30% bonus Total DMG. Triggering it again resets the duration',
                                priority: '2nd',
                            },
                            {
                                id: 3,
                                name: 'Grey & Empty',
                                desc: 'Enemies stay tainted for 5s longer',
                                priority: '3rd',
                            },
                            {
                                id: 4,
                                name: 'Blue & Cold',
                                desc: 'Triggering an Ultimate Evasion Skill taints enemies nearby with blue paint for 8s and reduces their Total DMG and Move Speed by 30%. Triggering it again resets the duration',
                                priority: '4th',
                            },
                            {
                                id: 5,
                                name: 'Nexus Signet: Shine like Stars',
                                desc: 'Core',
                                priority: '',
                            },
                            {
                                id: 6,
                                name: 'Blooming like Flowers',
                                desc: 'When enemies of countering types are tainted with both blue and red paints, Valkyries deal 50% bonus Total DMG to them (cannot stack)',
                                priority: 'YES',
                            }
                        ],
                    }
                ]
            }
        ]
    };
</script>
